### ISSUE TITLE
async def main(self)

### ISSUE THREAD

**Issue by PremyslCerny** [Plesoun/bspump_kafka#1]
https://github.com/Plesoun/bspump_kafka/blob/feature-init/bspump_kafka_app/app.py

Zkus kód vložit do init:

```python
def __init__(self):
		super().__init__()
		tvůj kód
```

Je ale zvláštní, že to nefunguje.

**Comment by Plesoun** [comment]
Takhle to funguje... Kdyby te napadlo proc, tak by me to zajimalo... :)
