### ISSUE TITLE
bspump.common.PPrintSink

### ISSUE THREAD

**Issue by PremyslCerny** [Plesoun/bspump_kafka#2]
Každá pipeline může mít jenom jeden sink (ne více), proto tento kód nefunguje:
https://github.com/Plesoun/bspump_kafka/blob/feature-init/bspump_kafka_app/pipeline.py

Stačí, když odstraníš řádek bspump.common.PPrintSink...

**Comment by Plesoun** [comment]
To jsem tam zapomnel z testovani :).
