### ISSUE TITLE
 bspump.common.MappingItemsProcessor

### ISSUE THREAD

**Issue by PremyslCerny** [Plesoun/bspump_kafka#4]
Tento procesor  bspump.common.MappingItemsProcessor vůbec nemusíš používat, můžeš si vytvořit vlastní s metodou process. Třeba:

class MySuperProcessor(bspump.Processor):

	def __init__(self, app, pipeline, id=None, config=None):
		super().__init__(app, pipeline, id, config)

	def process(self, context, event):
		event["a"] = "aaaa"
		return event  # Pass event to the following processor

https://github.com/Plesoun/bspump_kafka/blob/feature-init/bspump_kafka_app/pipeline.py

**Comment by Plesoun** [comment]
Dobre, ale k cemu to je? Z tohohle to nejak nemuzu rozklicovat... Muzu na zaklade nejakyho eventu predat context jinam?

**Comment by PremyslCerny** [comment]
Ne, context je sdílen mezi všemi událostmi v daném zpracování, tj. například při čtení souboru po řádcích je každý řádek jedna eventa, zatímco v contextu mají všechny stejný název souboru (čte se z jednoho souboru).

Jednotlivé typy procesorů jsou popsány tady: https://docs.libertyaces.com/content/50-software-engineering/00-index.html

Můžeš je použít pro enrichement, parsování atd. Například ten MappingItemsProcessor převede dictionary na list.

**Comment by Plesoun** [comment]
Super, pridal jsem si k tomu jsonu pomoci tohodle novej key: value pair.
