### ISSUE TITLE
Vytváření vlastního sinku

### ISSUE THREAD

**Issue by PremyslCerny** [Plesoun/bspump_kafka#5]
Vytváření vlastního sinku je možné, Franta ti ukáže jak na to (dělá teď SSHSink atp.). Obyčejně pak dáme pull request přímo do BSPumpy, takže všechny sinky máme na jednom místě. Sink vypadá třeba takhle:

class PPrintSink(Sink):

	def __init__(self, app, pipeline, id=None, config=None, stream=None):
		super().__init__(app, pipeline, id, config)
		self.Stream = stream if stream is not None else sys.stdout

	def process(self, context, event):
		pprint.pprint(event, stream=self.Stream)

**Comment by Plesoun** [comment]
Ok, zkusim se taky podivat na nejake dalsi uz hotove sinky.
